### ISSUE TITLE
Getting error on example

### ISSUE THREAD

**Issue by imemohit** [dirkolbrich/yahoo-finance-query#11]
I just went to 
http://code.dirkolbrich.de/YahooFinanceQuery/example.php
for 
function quote($symbol[, $params]);
wrote CAJ, got the following once.

Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (N/A N/A) at position 1 (/): Unexpected character' in /is/htdocs/wp1151455_Z2YVKT0TI9/code/YahooFinanceQuery/YahooFinanceQuery.php:304 Stack trace: #0 /is/htdocs/wp1151455_Z2YVKT0TI9/code/YahooFinanceQuery/YahooFinanceQuery.php(304): DateTime->__construct('N/A N/A', Object(DateTimeZone)) #1 /is/htdocs/wp1151455_Z2YVKT0TI9/code/YahooFinanceQuery/example.php(71): YahooFinanceQuery\YahooFinanceQuery->quote(Array, Array) #2 {main} thrown in /is/htdocs/wp1151455_Z2YVKT0TI9/code/YahooFinanceQuery/YahooFinanceQuery.php on line 304

**Comment by dirkolbrich** [comment]
Confirmed. Missing error handling in my script. If the stock is not traded or the market is closed, the quote() request will return a N/A for the trading time. Will fix it...

**Comment by dirkolbrich** [comment]
fixed with commit https://github.com/dirkolbrich/yahoo-finance-query/commit/c17de89aec60e43b315a407ad7c0e6613a24ea2e
