### ISSUE TITLE
SymbolSuggest is broken

### ISSUE THREAD

**Issue by rassom** [dirkolbrich/yahoo-finance-query#13]
Try for example this URL (from the SymbolSuggest.php file, inserted with the symbol "C" for Citigroup stock): 
http://d.yimg.com/autoc.finance.yahoo.com/autoc?query=C&callback=YAHOO.Finance.SymbolSuggest.ssCallback

Someone else experiencing the problem:
https://stackoverflow.com/questions/32899143/yahoo-finance-api-stock-ticker-lookup-only-allowing-exact-match

Any ideas how to fix?

**Comment by dirkolbrich** [comment]
Seems like Yahoo changed the way their Symbol Suggest Callback works. I traced it back to the new query. The base url has changed as well as the necessary options.

`http://d.yimg.com/aq/autoc?query=basf&region=US&lang=en-US&callback=YAHOO.util.ScriptNodeDataSource.callbacks`

You have to provide region and language with each request. Both have to match. Another region gives another result. If they don't match or no region&lang is provided, no result will be given back.

The above query gives back:
```json
YAHOO.util.ScriptNodeDataSource.callbacks({"ResultSet":{"Query":"basf","Result":[
{"symbol":"BAS.DE","name":"BASF SE","exch":"GER","type":"S","exchDisp":"XETRA","typeDisp":"Equity"},
{"symbol":"BASFY","name":"BASF SE","exch":"PNK","type":"S","exchDisp":"OTC Markets","typeDisp":"Equity"},
{"symbol":"BAS.F","name":"BASF N","exch":"FRA","type":"S","exchDisp":"Frankfurt","typeDisp":"Equity"},
{"symbol":"BASF.BO","name":"BASF India Limited","exch":"BSE","type":"S","exchDisp":"Bombay","typeDisp":"Equity"},
{"symbol":"BASA.BE","name":"BASF SE SP ADR","exch":"BER","type":"S","exchDisp":"Berlin","typeDisp":"Equity"},
{"symbol":"BASF.NS","name":"BASF India Limited","exch":"NSI","type":"S","exchDisp":"NSE","typeDisp":"Equity"},
{"symbol":"BFA.L","name":"BASF SE","exch":"LSE","type":"S","exchDisp":"London","typeDisp":"Equity"},
{"symbol":"BASFX","name":"BMO Short Tax-Free A","exch":"NAS","type":"M","exchDisp":"NASDAQ","typeDisp":"Fund"},
{"symbol":"BASA.F","name":"BASF SE SP ADR","exch":"FRA","type":"S","exchDisp":"Frankfurt","typeDisp":"Equity"},
{"symbol":"BASF.MI","name":"BASF SE","exch":"MIL","type":"S","exchDisp":"Milan","typeDisp":"Equity"}]}});
```

While changing the region to DE:
`http://d.yimg.com/aq/autoc?query=basf&region=DE&lang=de-DE&callback=YAHOO.util.ScriptNodeDataSource.callbacks`
gives back, which is a slightly different result with localized display types:

```JSON
YAHOO.util.ScriptNodeDataSource.callbacks({"ResultSet":{"Query":"basf","Result":[
{"symbol":"BAS.DE","name":"BASF SE","exch":"GER","type":"S","exchDisp":"XETRA","typeDisp":"Aktie"},{"symbol":"BAS.F","name":"BASF N","exch":"FRA","type":"S","exchDisp":"Frankfurt","typeDisp":"Aktie"},
{"symbol":"BASG.EX","name":"BASF N","exch":"EUX","type":"S","exchDisp":"Eurex","typeDisp":"Aktie"},
{"symbol":"BASFY","name":"BASF SE","exch":"PNK","type":"S","exchDisp":"OTC-Märkte","typeDisp":"Aktie"},
{"symbol":"BFA.L","name":"BASF SE","exch":"LSE","type":"S","exchDisp":"London","typeDisp":"Aktie"},
{"symbol":"BAS.HA","name":"BASF N","exch":"HAN","type":"S","exchDisp":"Hannover","typeDisp":"Aktie"},
{"symbol":"BASA.DE","name":"BASF SE","exch":"GER","type":"S","exchDisp":"XETRA","typeDisp":"Aktie"},
{"symbol":"BAS.BE","name":"BASF N","exch":"BER","type":"S","exchDisp":"Berlin","typeDisp":"Aktie"},
{"symbol":"BAS.DU","name":"BASF N","exch":"DUS","type":"S","exchDisp":"Düsseldorf","typeDisp":"Aktie"},
{"symbol":"BAS.HM","name":"BASF N","exch":"HAM","type":"S","exchDisp":"Hamburg","typeDisp":"Aktie"}]}});
```

I will update YahooFinanceQuery accordingly.

Thanks for the hint.

**Comment by rassom** [comment]
@dirkolbrich Thank you :)   PS. Do you know how to broaden the search to return more than 10 results?

**Comment by dirkolbrich** [comment]
Sorry, not with a son response. Best way I could come up would be a screen scrapper which fetches all results from `http://finance.yahoo.com/lookup?s=basf`.

**Comment by rassom** [comment]
Thanks :)
