### ISSUE TITLE
Code mistakes

### ISSUE THREAD

**Issue by klodoma** [dirkolbrich/yahoo-finance-query#14]
Hi, 

Your approach is good, but there are issues in the code. 
```php
if ($this->response['status'] = 404) {
```

is an assignment. This will ALWAYS be true. 
Should be == instead of =

Even better put the constant in front:
```php
if (404 == $this->response['status']) {
```
Regards, Andrei.

**Comment by dirkolbrich** [comment]
Thanks for the tip, will change rewrite the code.

In fact, you could have left the title to "Rookie mistakes" ;-)
