### ISSUE TITLE
Misguidance at README

### ISSUE THREAD

**Issue by brnluiz** [dirkolbrich/yahoo-finance-query#7]
The README is wrong when it says to use

```php
$query = new YahooFinanceQuery\YahooFinanceQuery;
```

To use this implementation that you wrote, I did:
```php 
use DirkOlbrich\YahooFinanceQuery;
// [...] 
$query = new YahooFinanceQuery\YahooFinanceQuery;
```

As I wanted a cleaner code, I declared it as:
```php 
use DirkOlbrich\YahooFinanceQuery\YahooFinanceQuery; 
// [...] 
$query = new YahooFinanceQuery;
```

**Comment by dirkolbrich** [comment]
You're right. The was like the README says work only in you use YahooFinanceQuery as a standalone class, not via Composer. I'll Update the Readme.

Thanks for your help..
